### ISSUE TITLE
If search fails.

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Classic-Motorcycles#4]
Search can fail in 2 ways.
1. No result. "Let us know what you have so we can improve our results"
2. Wrong result. "Do you think we got it wrong, let us know"
Using the wording above, let the user enter into a text box what this think the result should have been.
Record this and the search into the db

**Comment by pedro-walter** [comment]
After the feedback is recorded, should I send the user back to the homepage? Or should I use some AJAX to make the form look nicer?

**Comment by vincentdavis** [comment]
Do what you think looks best.
